### ISSUE TITLE
Pull changes for M1 chip back into docker-magento

### ISSUE THREAD

**Issue by markshust** [luancschmitz/docker-magento-mac-m1#2]
**Description**

Hey there, great fork! I'd be interested in pulling these changes into the main docker-magento repo, granted the changes are fairly straight-forward, don't modify too many files and are backwards-compatible with non-M1 chips. If you are interested, let me know and perhaps I can start a branch/PR with the changes to work on.

**Comment by luancschmitz** [comment]
Hi, glad to hear that.

As for the modifications working with non-M1 chips, I don't think it's possible. Because in the m1 docker, when I created this fork it was not possible to use x86 libs. With that I needed to change the x86 libs to ARM.
Here are some examples:

https://github.com/luancschmitz/docker-magento-mac-m1/blob/master/compose/images/php/Dockerfile

If you look at line 50, the ionCube is being downloaded for the ARM architecture and not x86. This is also true for other files.
I don't have much knowledge, but maybe if I can get the architecture of the computer that is doing the installation, it will be possible to download according to the architecture.

Same thing happens in nginx file:
https://github.com/luancschmitz/docker-magento-mac-m1/blob/master/compose/images/nginx/Dockerfile
on line 19.

and i changed the mail server to chickling/mailcatcher as mailhog/mailhog was not compatible with ARM chips.

Even docker developers recommend using only ARM libs to avoid incompatibilities.

**Comment by markshust** [comment]
@luancschmitz thanks for the update. Do you know if there is any way to test if images will work on an M1 chip if you are on an Intel chip? I'd love to hack away at this to find out what works, but am still on Intel (waiting for M2's).

**Comment by luancschmitz** [comment]
This as far as I know is not possible, as it is hardware related.
But if it's on m1 it's even possible to "emulate" x86 in the docker, but according to this issue in the docker for m1, x86 libs in arm can give problems. (Especially the last comment)

https://github.com/docker/for-mac/issues/5204#issuecomment-876289068

For example, the most common one when using your repository (when you hadn't created the fork with these changes to m1) was the "out of memory". Even though the docker has enough memory.

But to test this repository you would need an ARM chip.

**Comment by drpayyne** [comment]
Hi @markshust and @luancschmitz, I've just set up this repo on an Apple Silicon machine and it works good. Just letting you know that I can contribute to M1 development if required!

**Comment by markshust** [comment]
Thanks @drpayyne, I don't yet have an M1 chip (waiting for M1X) but the goal would be to make the main docker-magento repo compatible with M1, in the least invasive way possible (only necessary changes needed to get it to work with M1, while also working with non-M1 chips). If you can open a PR, we can work on it until it works for both of us, then pull it in.

**Comment by drpayyne** [comment]
@markshust, I've created the first issue for this work - https://github.com/markshust/docker-magento/issues/511. Thanks!

**Comment by markshust** [comment]
FYI ARM support landed in docker-magento 40.0.0 🎉
